name: practices
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  get_it: ^8.0.3
  http: ^1.2.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/ic_photo.png
    - assets/icons/arrow.svg

